server:
  port: 8080

spring:
  application:
    name: demo
  
  # 数据库配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=aww_test
    username: postgres
    password: yoyac123
  
  # JPA 配置
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update 